name: Lint

on:
    pull_request:
        branches:
            - dev

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-20.04

        steps:
            - name: git Checkout
              uses: actions/checkout@v3

            - name: node 환경 설정
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: 의존성 체크
              run: yarn

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  eslint: true
                  prettier: true
