name: '@vircle/entity'
on:
    pull_request:
        branches:
            - dev
        paths:
            - 'packages/entity/**'

jobs:
    test-coverage:
        timeout-minutes: 5
        permissions:
            checks: write
            pull-requests: write
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.SECRET_TOKEN }}
            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  package-manager: yarn
                  test-script: yarn jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
                  working-directory: ./packages/entity
