name: '@vircle/entity'
on:
    pull_request:
        branches:
            - dev
        paths:
            - 'packages/entity/**'

jobs:
    test-coverage:
        timeout-minutes: 10
        permissions:
            checks: write
            pull-requests: write
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.SECRET_TOKEN }}

            - name: node 환경 설정
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: artiomtr/jest-coverage-report-action@v2
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  package-manager: yarn
                  test-script: yarn jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
                  working-directory: ./packages/entity
